name: mirror

on: [push, delete, pull_request]

jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pixta-dev/mirror-action@v1
        with:
          target_repo_url:
            - ${{ env.TARGET_REPO_URL }}
          ssh_private_key:
            - ${{ secrets.SSH_PRIVATE_KEY }}

