name: Mirror Evol'Os to Epitech Repo
on:
  push:
    branches:
      - '*'

jobs:
  mirror_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Bot
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch content
        run: |
          git fetch -p origin

      - name: Push on Epitech repo
        env:
          SCHOOL_REPO_A: ${{ secrets.SCHOOL_REPO_A}}
        run: |
          #git remote add epitech https://x-access-token:$SCHOOL_REPO_A@github.com/EpitechPromo2026/G-EIP-700-RUN-7-1-eip-apolline.fontaine.git
          git remote -v
          #git push --mirror epitech
      - run: echo "Job status is ${{ job.status }}."