name: mirror

on: [push, delete, pull_request]

jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/G-EIP-700-RUN-7-1-eip-apolline.fontaine.git
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}

